### ISSUE TITLE
Question about the Core Distance of an Object formula

### ISSUE THREAD

**Issue by avouros** [christopherjenness/DBCV#10]
Thank you very much for providing the code for the DBCV index.

I noticed in the `_core_dist` function that you have defined the number of neighbours (`n_neighbors`) to equal the dimensionality of the dataset `np.shape(neighbors)[1]` _(Line 57 of the DBCV.py)_ shouldn't this have been `np.shape(neighbors)[0]` ? 

Also based on the formula of [Moulavi et al](https://epubs.siam.org/doi/abs/10.1137/1.9781611973440.96) _(definition 1, equation 3.1)_ Line 62 of your code shouldn't have been `core_dist = (numerator / (n_neighbors` **-1** `)) ** (-1/n_features)` ?

**Comment by joaopastor** [comment]
I agree with you @avouros 
I did modify this to use a precomputed distance matrix and your tip helped a lot.

**Comment by onofricamila** [comment]
If `np.shape(neighbors)[0]` is taken instead of `np.shape(neighbors)[1]` (as it should be), the resultant index has always a low value (hardly never a positive one) ... even when evaluating good clustering results as the one obtaining running hdbscan with the noisy moons dataset (provided by the author). 

Does anyone know why?

**Comment by christopherjenness** [comment]
Fixed: https://github.com/christopherjenness/DBCV/commit/d874292eafc88b6f62f1294667c24ed3d780bf9c

**Comment by pancodia** [comment]
@onofricamila I have the same observation. Do you have any insights on this? I am wondering if something is wrong.
